version: "3.6"

services:
  node-app:
    container_name: node-app
    build:
      context: ./node-app
    volumes:
      - $HOME/.aws/:/root/.aws/
    ports:
      - "9090:8080"
    env_file:
      - .env
